---

- hosts: all
  become: true
  tasks:
  
  - name: update repository index
    apt:
      update_chache: yes
    when: ansible_distribution == "ubuntu"

  - name: install apache2 package
    apt:
      name: apache2
    when: ansible_distribution == "ubuntu"
  - name: add php support for apache
    apt:
      name: libapache2-mod-php
