---

- hosts: all
  become: true
  tasks:
  
  - name: update repository index
    apt:
      update_chache: yes
    when: ansible_distribution == "ubuntu"

  - name: install apache2 and php packages for ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "ubuntu"


- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (Ubuntu)
    apt: 
      name: mariadb-server
      state: present
    when: ansible_distribution == "Ubuntu"

