---

- hosts: web_servers
  become: true
  tasks:
  
  - name: update repository index
    apt:
      update_chache: yes
    when: ansible_distribution == "ubuntu"

  - name: install apache2 and php packages for ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "ubuntu"
    
  - name: copy default html file for site
    tags: apache,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (Ubuntu)
    apt: 
      name: mariadb-server
      state: present
    when: ansible_distribution == "Ubuntu"

